import { Friend, Event, User } from './types';

export const COLORS = {
  primary: '#90d8b2',
  secondary: '#8dd2dd',
  accent1: '#8babf1',
  accent2: '#8b95f6',
  accent3: '#9b8bf4',
};

export const MOCK_USER: User = {
  id: 'me',
  firstName: 'Rose',
  lastName: 'Mary',
  email: 'rose@example.com',
  profilePicture: 'https://picsum.photos/seed/rose/200',
  yearOfStudy: '3rd Year',
  major: 'Computer Science',
  bio: "Hey, I'm Rose, and I love debate, singing, and Ace Attorney! Looking for friends :) Always looking for new cafe recommendations, so if you have any good ones, share them with me!",
  hobbies: ['Debate', 'Singing', 'Coffee', 'Rock Climbing', 'Music', 'Dance'],
  personality: {
    calmVsEnergetic: 40,
    spontaneousVsPlanned: 60,
  },
  qualities: ['Loyal', 'Creative', 'Funny'],
  improvements: ['Procrastination', 'Public Speaking', 'Waking up early'],
  friendQuality: 'Honesty',
  dealbreaker: 'Dishonesty',
  scheduleVisibility: 'friends',
  schedule: {
    'Tue': ['14:00', '15:00'],
    'Sat': ['14:00', '15:00'],
  },
};

export const MOCK_FRIENDS: Friend[] = [
  {
    id: 'jack',
    firstName: 'Jack',
    lastName: 'Smith',
    email: 'jack@example.com',
    profilePicture: 'https://picsum.photos/seed/jack/200',
    yearOfStudy: '4th Year',
    major: 'Software Engineering',
    bio: 'Hey, I\'m Jack. I live for those late-night vibe coding sessions where the lo-fi playlist hits just right. Nothing beats the zen of debugging to chill beats and calling it "progress" at 3 a.m.',
    hobbies: ['Vibe Coding', 'Lo-fi', 'Gaming'],
    personality: { calmVsEnergetic: 30, spontaneousVsPlanned: 80 },
    qualities: ['Analytical', 'Patient', 'Focused'],
    improvements: ['Sleep schedule', 'Socializing', 'Exercise'],
    friendQuality: 'Intelligence',
    dealbreaker: 'Loud chewers',
    scheduleVisibility: 'everyone',
    schedule: { 'Thu': ['14:00', '15:00'] },
    status: 'Recently attended a concert',
    lastActivity: '1d',
  },
  {
    id: 'lily',
    firstName: 'Lily',
    lastName: 'Singh',
    email: 'lily@example.com',
    profilePicture: 'https://picsum.photos/seed/lily/200',
    yearOfStudy: '2nd Year',
    major: 'Art History',
    bio: 'Hi, I\'m Lily and coffee is basically my personality at this point. I\'m always chasing the perfect pour-over, and turning every café visit into a mini adventure ;D',
    hobbies: ['Coffee', 'Art', 'Photography'],
    personality: { calmVsEnergetic: 70, spontaneousVsPlanned: 30 },
    qualities: ['Adventurous', 'Kind', 'Observant'],
    improvements: ['Time management', 'Cooking', 'Saving money'],
    friendQuality: 'Curiosity',
    dealbreaker: 'Bad coffee',
    scheduleVisibility: 'friends',
    schedule: { 'Tue': ['14:00', '15:00'], 'Sat': ['14:00', '15:00'] },
    status: 'Recently visited an Art Gallery',
    lastActivity: '1d',
  },
  {
    id: 'bree',
    firstName: 'Bree',
    lastName: 'Collins',
    email: 'bree@example.com',
    profilePicture: 'https://picsum.photos/seed/bree/200',
    yearOfStudy: '3rd Year',
    major: 'Film Studies',
    bio: 'I\'m Bree and I live for my passion for film. I chase moody lighting and raw stories, and spent my time sketching frames, and editing until the sun comes up :P',
    hobbies: ['Film', 'Photography', 'Art'],
    personality: { calmVsEnergetic: 20, spontaneousVsPlanned: 90 },
    qualities: ['Passionate', 'Dedicated', 'Artistic'],
    improvements: ['Public speaking', 'Networking', 'Cooking'],
    friendQuality: 'Creativity',
    dealbreaker: 'Spoilers',
    scheduleVisibility: 'friends',
    schedule: { 'Mon': ['09:00', '17:00'], 'Sun': ['17:00', '20:00'] },
    status: 'Watching a classic noir',
    lastActivity: '3h',
  },
  {
    id: 'jay',
    firstName: 'Jay',
    lastName: 'Pritchett',
    email: 'jay@example.com',
    profilePicture: 'https://picsum.photos/seed/jay/200',
    yearOfStudy: 'Alumni',
    major: 'Business',
    bio: 'CEO of Pritchett\'s Closets & Blinds, built it from the ground up. I like golf, my Stella, and a quiet beer.',
    hobbies: ['Pets', 'Golf', 'Closets'],
    personality: { calmVsEnergetic: 10, spontaneousVsPlanned: 100 },
    qualities: ['Hardworking', 'Direct', 'Protective'],
    improvements: ['Patience', 'Technology', 'Expressing feelings'],
    friendQuality: 'Reliability',
    dealbreaker: 'Laziness',
    scheduleVisibility: 'everyone',
    schedule: { 'Sat': ['09:00', '18:00'], 'Sun': ['09:00', '18:00'] },
    status: 'Golfing at the club',
    lastActivity: '5h',
  },
  {
    id: 'phil',
    firstName: 'Phil',
    lastName: 'Dunphy',
    email: 'phil@example.com',
    profilePicture: 'https://picsum.photos/seed/phil/200',
    yearOfStudy: 'Alumni',
    major: 'Marketing',
    bio: 'I\'m a cool dad, that\'s my thing. I\'m hip, I surf the web, I text. LOL: Laugh Out Loud. OMG: Oh My God. WTF: Why The Face.',
    hobbies: ['Magic', 'Real Estate', 'Trampolining'],
    personality: { calmVsEnergetic: 100, spontaneousVsPlanned: 10 },
    qualities: ['Optimistic', 'Fun', 'Supportive'],
    improvements: ['Focus', 'Safety', 'Technology'],
    friendQuality: 'Enthusiasm',
    dealbreaker: 'Negativity',
    scheduleVisibility: 'everyone',
    schedule: { 'Sat': ['10:00', '14:00'] },
    status: 'Practicing a new magic trick',
    lastActivity: '10m',
  },
];

export const MOCK_RECOMMENDED: Friend[] = [
  {
    id: 'emma',
    firstName: 'Emma',
    lastName: 'Smithington',
    email: 'emma@example.com',
    profilePicture: 'https://picsum.photos/seed/emma/200',
    yearOfStudy: '1st Year',
    major: 'Global Studies',
    bio: 'Hey! I’m Emma and I love trying new foods (especially anything spicy), exploring new places and enjoying myself!',
    hobbies: ['Food', 'Travel', 'Spicy Food'],
    personality: { calmVsEnergetic: 90, spontaneousVsPlanned: 20 },
    qualities: ['Outgoing', 'Energetic', 'Open-minded'],
    improvements: ['Focus', 'Organization', 'Budgeting'],
    friendQuality: 'Energy',
    dealbreaker: 'Boring people',
    scheduleVisibility: 'everyone',
    schedule: { 'Mon': ['09:00', '17:00'], 'Sun': ['17:00', '20:00'] },
    status: 'Exploring a new taco spot',
  },
  {
    id: 'nathan',
    firstName: 'Nathan',
    lastName: 'Young',
    email: 'nathan@example.com',
    profilePicture: 'https://picsum.photos/seed/nathan/200',
    yearOfStudy: '2nd Year',
    major: 'Culinary Arts',
    bio: 'Hello! I love baking and have baked cakes for my friends. I like to experiment with new flavors and textures.',
    hobbies: ['Baking', 'Cooking', 'Food Styling'],
    personality: { calmVsEnergetic: 50, spontaneousVsPlanned: 50 },
    qualities: ['Generous', 'Creative', 'Patient'],
    improvements: ['Cleaning up', 'Time management', 'Public speaking'],
    friendQuality: 'Appreciation',
    dealbreaker: 'Pickey eaters',
    scheduleVisibility: 'friends',
    schedule: { 'Wed': ['18:00', '21:00'] },
    status: 'Baking a sourdough loaf',
  },
  {
    id: 'katie',
    firstName: 'Katie',
    lastName: 'Ju',
    email: 'katie@example.com',
    profilePicture: 'https://picsum.photos/seed/katie/200',
    yearOfStudy: '3rd Year',
    major: 'Business Administration',
    bio: 'Hello guysss! I am Katie and I’m a business major at my dream University. I love networking and meeting new people!',
    hobbies: ['Networking', 'Tennis', 'Reading'],
    personality: { calmVsEnergetic: 60, spontaneousVsPlanned: 70 },
    qualities: ['Ambitious', 'Organized', 'Social'],
    improvements: ['Relaxing', 'Work-life balance', 'Cooking'],
    friendQuality: 'Ambition',
    dealbreaker: 'Lack of motivation',
    scheduleVisibility: 'friends',
    schedule: { 'Fri': ['15:00', '18:00'] },
    status: 'Studying at the library',
  }
];

export const MOCK_REQUESTS: Friend[] = [
  {
    id: 'request1',
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'alex@example.com',
    profilePicture: 'https://picsum.photos/seed/alex/200',
    yearOfStudy: '2nd Year',
    major: 'Psychology',
    bio: 'Hey! I love understanding how people think. Looking for study buddies and coffee enthusiasts.',
    hobbies: ['Reading', 'Chess', 'Hiking'],
    personality: { calmVsEnergetic: 20, spontaneousVsPlanned: 80 },
    qualities: ['Empathetic', 'Thoughtful', 'Reliable'],
    improvements: ['Overthinking', 'Public speaking', 'Cooking'],
    friendQuality: 'Empathy',
    dealbreaker: 'Arrogance',
    scheduleVisibility: 'friends',
    schedule: { 'Mon': ['10:00', '12:00'] },
    status: 'Reading a new book',
    lastActivity: '2h',
  },
  {
    id: 'request2',
    firstName: 'Sarah',
    lastName: 'Miller',
    email: 'sarah@example.com',
    profilePicture: 'https://picsum.photos/seed/sarah/200',
    yearOfStudy: '3rd Year',
    major: 'Architecture',
    bio: 'Architecture student who loves sketching and urban exploration. Always down for a walk in the city.',
    hobbies: ['Sketching', 'Photography', 'Walking'],
    personality: { calmVsEnergetic: 40, spontaneousVsPlanned: 60 },
    qualities: ['Creative', 'Detail-oriented', 'Curious'],
    improvements: ['Sleep', 'Time management', 'Exercise'],
    friendQuality: 'Creativity',
    dealbreaker: 'Negativity',
    scheduleVisibility: 'friends',
    schedule: { 'Wed': ['14:00', '16:00'] },
    status: 'Sketching at the park',
    lastActivity: '5h',
  }
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Coffee with Lily',
    description: 'Casual coffee hangout at the new cafe downtown.',
    image: 'https://picsum.photos/seed/coffee/800/600',
    date: '2025-09-09',
    time: '2pm - 3pm',
    location: 'Downtown Cafe',
    attendees: ['lily'],
    isRSVPed: true,
    creatorId: 'lily',
  },
  {
    id: '2',
    title: 'Rock Climbing with Jay',
    description: 'Weekly rock climbing session at the gym.',
    image: 'https://picsum.photos/seed/climbing/800/600',
    date: '2025-09-11',
    time: '2pm - 3pm',
    location: 'The Rock Gym',
    attendees: ['jay'],
    isRSVPed: true,
    creatorId: 'jay',
  },
  {
    id: '3',
    title: 'CSSU Party',
    description: 'The biggest party of the semester! RSVP link in bio!',
    image: 'https://picsum.photos/seed/party/800/600',
    date: '2025-09-22',
    time: '7pm - 3am',
    location: 'Student Union Hall',
    attendees: ['jack', 'jay'],
    price: '$5',
    isRSVPed: false,
    creatorId: 'jack',
  },
];
